#suppress inspection "UnusedProperty" for whole file
.longName=Drauven Blood
.name=Drauven Blood
.blurb=If <name> is missing health, <self.mf:he/she/they> will regain some at the end of <self.mf:his/her/their> turn. [b](<int:3+(max(1,(self.POTENCY/3))*self.drauvenDeck_mystic_dragonBlood) - (self.numUses|drauvenBlood)> uses left this battle)[]