#suppress inspection "UnusedProperty" for whole file
.blurb=<name> empowers a friendly Drauven, improving Drauven Blood healing by [b]1[] health per activation and removing [:statusEffect.poisoned]Poisoned[], [:statusEffect.blinded]Blinded[], and [:statusEffect.deafened]Deafened[].
.longName=Dragon Blood
.name=Dragon Blood
