#suppress inspection "UnusedProperty" for whole file
.blurb=<name>'s Razorbeak harries an enemy, reducing their speed and dealing [b]<int:2+floor(self.POTENCY/2)>[] shred or damage at the start of the enemy's turn for up to 3 turns.
.formula=Shred or Damage: 2 + 1/2 Potency
.longName=Harass
.name=Harass
