#suppress inspection "UnusedProperty" for whole file
.blurb=Launch a spear to pierce enemies, [:statusEffect.pinned]pinning[] <self.drauvenDeck_mystic_battlecrafting_upgrade:them/a directly targeted enemy>.
.formula=Damage: (2 to 3) + (Potency + Spell Damage)\nPierce: 2 + Potency
.longName=Javelin
.name=Javelin
