name: 'New Release Notification'
env: 
  SERVER: deploy
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: https://discord.com/api/webhooks/1248824682401107988/23AjTwsfgt720Bb_-P7OSXLeXWgJmVwK8G_mWuj7MsNjQUUNwUd-sbGMl8epGjEo2cax
          title: New Release!
          message: "**${{ github.event.release.title }}**\n\n**Details:** \n${{ github.event.release.body }}\n\n$[Full Details]({{ github.event.release.html_url }})"
          include_image: true
          avatar_url: https://github.com/BoldestDungeon/wildermyth-drauven-pcs/blob/main/GitHubBotAvatar.png
          username: Trava
  workshopUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: 763890
          publishedFileId: 2810606541
          buildDescription: ${{ github.event.release.title }}\n\n${{ github.event.release.body }}
